import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "black" },
  cameraPreview: { ...StyleSheet.absoluteFillObject },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  focusFrame: {
    width: 330,
    height: 500,
    borderWidth: 2,
    borderColor: "#007AFF",
    borderRadius: 16,
  },
  instruction: {
    color: "white",
    marginTop: 24,
    fontSize: 16,
    fontWeight: "bold",
  },

  reviewOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  reviewCard: {
    width: "100%",
    backgroundColor: "#1C1C1E",
    borderRadius: 20,
    padding: 30,
    alignItems: "center",
  },
  reviewLabel: {
    color: "#8E8E93",
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 15,
  },
  reviewInput: {
    color: "white",
    fontSize: 48,
    fontWeight: "900",
    borderBottomWidth: 3,
    borderBottomColor: "#007AFF",
    width: "100%",
    textAlign: "center",
    marginBottom: 30,
  },
  reviewActionGroup: { flexDirection: "row", gap: 15 },
  retryButton: {
    flex: 1,
    backgroundColor: "#3A3A3C",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
  },
  retryText: { color: "white", fontWeight: "bold" },
  confirmButton: {
    flex: 1,
    backgroundColor: "#34C759",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
  },
  confirmText: { color: "white", fontWeight: "bold" },

  bottomBar: {
    position: "absolute",
    bottom: 30,
    width: "100%",
    padding: 20,
    backgroundColor: "rgba(0,0,0,0.85)",
    borderRadius: 20,
    alignItems: "center",
  },
  status: { color: "#8E8E93", marginBottom: 20, fontSize: 14 },
  syncButton: {
    width: "100%",
    backgroundColor: "#2C2C2E",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#3A3A3C",
  },
  syncText: { color: "#FFD700", fontWeight: "bold", fontSize: 16 },
  buttonDisabled: { opacity: 0.5 },
});
